/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CareTimeline: typeof import('./src/components/CareTimeline.vue')['default']
    PhotoGrid: typeof import('./src/components/PhotoGrid.vue')['default']
    PlantCard: typeof import('./src/components/PlantCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
